// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  vec3 white = vec3(1.0, 1.0, 1.0);
  vec3 n = normalize(normal_fs_in);
  vec3 v = normalize(-view_pos_fs_in.xyz);
  float theta = M_PI * animation_seconds / 4.0;
  float x = cos(theta);
  float z = sin(theta);
  vec3 l = normalize(vec3(x, 1.0, z));
  vec3 baseColor = mix(vec3(0.0, 0.0, 1.0), vec3(0.5, 0.5, 0.5), float(is_moon));
  baseColor += 0.5 * perlin_noise(sphere_fs_in * 3) + 0.5;
  color = blinn_phong(baseColor, baseColor, white, 1000.0, n, v, l);
}
